### PR TITLE
Fix use of deprecated class

### PR DESCRIPTION
**Pull request by neilime**
Supports twig > 1.21 : https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L96

### CODE REVIEW

**Comment by kachar** [comment]
Any plan to merge this hotfix to `master` branch?

**Comment by kokspflanze** [comment]
@kachar i have that part in my fork, if you want to use it. https://github.com/kokspflanze/ZfcTwig/blob/1.4.1/src/ZfcTwig/Twig/EnvironmentFactory.php#L36
https://github.com/kokspflanze/ZfcTwig/blob/1.4.1/src/ZfcTwig/Twig/FallbackFunction.php#L24

also works with twig1|2 (twig2 just with zf3 and php7)

**Comment by trylika** [comment]
when is it going to be merged?

**Comment by kusmierz** [comment]
@kokspflanze any news here?

**Comment by kokspflanze** [comment]
@kusmierz like i wrote use my fork https://packagist.org/packages/kokspflanze/zfc-twig that has that fix, about this repo i can not say smth.

**Pull request closed without merging**
